### ISSUE TITLE
big bug in autojoin

### ISSUE THREAD

**Issue by lexo13** [envms/fluentpdo#187] opened 2016-10-28 14:17 UTC
I've a big bug in autojoin like this (http://stackoverflow.com/questions/35508298/how-to-stop-fluentpdo-incorrectly-inferring-a-table-name) but not the same

$etab = ['GAM : BASSE MAJOR HEALTH FACILITY', 'GAM: KWINELLA HEALTH CENTER'];

```
    $Fpdo = new FPDO();
    $results = $Fpdo->from('rapsigl')
                    ->select(null)
                    ->select('rapsigl.code as rapsigl_code')
                    ->innerJoin('inventory')
                    ->where(['isreport' => 0, 'etab' => $etab])
                    ->fetchAll();
```

SELECT rapsigl.code as rapsigl_code FROM rapsigl INNER JOIN inventory ON inventory.id = rapsigl.inventory_id  LEFT JOIN GAM ON GAM.rapsigl_id = rapsigl.id WHERE isreport = ? AND etab IN ('GAM : BASSE MAJOR HEALTH FACILITY', 'GAM: KWINELLA HEALTH CENTER')

FPDO automaticaly add LEFT JOIN GAM ON GAM.rapsigl_id = rapsigl.id because of second value in array is GAM: and not GAM : (space)

It's a big bug for using classes

Sorry for my english

**Comment by cbornhoft** [comment] 2016-11-01 16:17
Thanks for reporting, we'll take a look.

**Comment by pascal-hofmann** [comment] 2017-10-10 10:41
Any update on this? FluentPDO adds absurd joins to queries just because some quoted string used somewhere in a statement contains a dot. IMHO this is a major bug and may even have security implications.

**Comment by pascal-hofmann** [comment] 2017-10-10 10:48
Duplicate of #177.

**Comment by cbornhoft** [comment] 2017-10-10 13:24
@pascal-hofmann I agree, it's definitely something that needs to be fixed, however it would introduce many breaking changes if we were to modify it now. As you mentioned, this duplicates #177 as well as many others.

For reference, the current solution is to disable smart join for the queries you know could potentially contain `.` or `:`:

    $query = $fpdo->from($table)->disableSmartJoin()->where("columnName", "env.ms");
    $nextQuery = $fpdo->from($otherTable)->enableSmartJoin()->where("otherColumn", "envms");

**Closed by cbornhoft** 2017-10-10 13:24 UTC
Labels: Bug
